CREATE TABLE mdm.ic00_admjd (
                                record_no varchar(128) NOT NULL,
                                original_record_no varchar(128) NULL,
                                adm_kod int8 NULL,
                                stran_kod varchar(128) NULL,
                                "name" varchar(60) NULL,
                                sname_rus varchar(7) NULL,
                                sname_lat varchar(7) NULL,
                                status varchar(128) NULL,
                                system_create_stamp timestamp NULL,
                                system_update_stamp timestamp NULL,
                                system_author_stamp varchar(128) NULL,
                                system_user_stamp varchar(128) NULL,
                                blocked_by_user varchar(128) NULL,
                                date_begin timestamp NULL,
                                date_end timestamp NULL,
                                record_union_no varchar(128) NULL,
                                active_flag int4 NULL,
                                version_no int8 NULL,
                                record_uuid varchar(128) NULL,
                                operation_type varchar(1) NULL,
                                protected_flag int4 NOT NULL DEFAULT 0,
                                revision int4 NULL,
                                external_id varchar(128) NULL,
                                CONSTRAINT ic00_admjd_pkey PRIMARY KEY (record_no)
);