CREATE TABLE main.ic00_admjd (
                                original_record_no varchar(128) NULL,
                                adm_kod integer NULL,
                                stran_kod varchar(128) NULL,
                                name varchar(60) NULL,
                                sname_rus varchar(7) NULL,
                                sname_lat varchar(7) NULL,
                                status varchar(128) NULL,
                                system_create_stamp timestamp NULL,
                                system_update_stamp timestamp NULL,
                                system_author_stamp varchar(128) NULL,
                                system_user_stamp varchar(128) NULL,
                                blocked_by_user varchar(128) NULL,
                                date_begin timestamp NULL,
                                date_end timestamp NULL,
                                record_union_no varchar(128) NULL,
                                active_flag integer NULL,
                                version_no integer NULL,
                                record_uuid varchar(128) NULL,
                                operation_type varchar(1) NULL,
                                protected_flag integer NOT NULL DEFAULT 0,
                                revision integer NULL,
                                external_id varchar(128) NULL
);